USE ROLE SPACEX_DATA_DEV_SYSADMIN;

USE DATABASE SPACEX_DATA_DEV;

USE SCHEMA STG_SPACEX_DATA;

-- Staging table for capsules
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_CAPSULES (
    CAPSULE_ID VARCHAR(16777216) NOT NULL,
    SERIAL VARCHAR(16777216),
    STATUS VARCHAR(16777216),
    DRAGON VARCHAR(16777216),
    REUSE_COUNT NUMBER (38, 0),
    WATER_LANDINGS NUMBER (38, 0),
    LAND_LANDINGS NUMBER (38, 0),
    LAST_UPDATE VARCHAR(16777216),
    LAUNCHES VARIANT,
    CREATED_AT VARCHAR(16777216),
    UPDATED_AT VARCHAR(16777216),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (CAPSULE_ID)
);

-- Staging table for company data
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_COMPANY (
    ID VARCHAR(16777216) NOT NULL,
    NAME VARCHAR(16777216),
    FOUNDER VARCHAR(16777216),
    FOUNDED NUMBER (38, 0),
    EMPLOYEES NUMBER (38, 0),
    VEHICLES NUMBER (38, 0),
    LAUNCH_SITES NUMBER (38, 0),
    TEST_SITES NUMBER (38, 0),
    CEO VARCHAR(16777216),
    CTO VARCHAR(16777216),
    COO VARCHAR(16777216),
    CTO_PROPULSION VARCHAR(16777216),
    VALUATION FLOAT,
    HEADQUARTERS VARIANT,
    LINKS VARIANT,
    SUMMARY VARCHAR(16777216),
    CREATED_AT VARCHAR(16777216),
    UPDATED_AT VARCHAR(16777216),
    RAW_DATA VARCHAR(16777216), -- Store complete JSON for future needs
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (ID)
);

-- Staging table for cores
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_CORES (
    CORE_ID VARCHAR(16777216) NOT NULL,
    SERIAL VARCHAR(256),
    BLOCK NUMBER (38, 0),
    STATUS VARCHAR(50),
    REUSE_COUNT NUMBER (38, 0),
    RTLS_ATTEMPTS NUMBER (38, 0),
    RTLS_LANDINGS NUMBER (38, 0),
    ASDS_ATTEMPTS NUMBER (38, 0),
    ASDS_LANDINGS NUMBER (38, 0),
    LAST_UPDATE VARCHAR(16777216),
    LAUNCHES VARCHAR(16777216),
    CREATED_AT VARCHAR(16777216),
    UPDATED_AT VARCHAR(16777216),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (CORE_ID)
);

-- Staging table for crew
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_CREW (
    CREW_ID VARCHAR(16777216) NOT NULL,
    NAME VARCHAR(256),
    AGENCY VARCHAR(256),
    IMAGE VARCHAR(16777216),
    WIKIPEDIA VARCHAR(16777216),
    STATUS VARCHAR(50),
    LAUNCHES VARCHAR(16777216),
    CREATED_AT VARCHAR(16777216),
    UPDATED_AT VARCHAR(16777216),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (CREW_ID)
);

-- Staging table for dragons
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_DRAGONS (
    DRAGON_ID VARCHAR(16777216) NOT NULL,
    NAME VARCHAR(256),
    TYPE VARCHAR(50),
    ACTIVE BOOLEAN,
    CREW_CAPACITY NUMBER (38, 0),
    SIDEWALL_ANGLE_DEG FLOAT,
    ORBIT_DURATION_YR NUMBER (38, 0),
    DRY_MASS_KG NUMBER (38, 0),
    DRY_MASS_LB NUMBER (38, 0),
    FIRST_FLIGHT DATE,
    HEAT_SHIELD VARCHAR(16777216),
    THRUSTERS VARCHAR(16777216),
    LAUNCH_PAYLOAD_MASS VARCHAR(16777216),
    LAUNCH_PAYLOAD_VOL VARCHAR(16777216),
    RETURN_PAYLOAD_MASS VARCHAR(16777216),
    RETURN_PAYLOAD_VOL VARCHAR(16777216),
    PRESSURIZED_CAPSULE VARCHAR(16777216),
    TRUNK VARCHAR(16777216),
    HEIGHT_W_TRUNK VARCHAR(16777216),
    DIAMETER VARCHAR(16777216),
    WIKIPEDIA VARCHAR(16777216),
    DESCRIPTION VARCHAR(16777216),
    FLICKR_IMAGES VARCHAR(16777216),
    CREATED_AT VARCHAR(16777216),
    UPDATED_AT VARCHAR(16777216),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (DRAGON_ID)
);

-- Staging table for history
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_HISTORY (
    HISTORY_ID VARCHAR(16777216) NOT NULL,
    TITLE VARCHAR(512),
    EVENT_DATE_UTC TIMESTAMP_NTZ (9),
    EVENT_DATE_UNIX NUMBER (38, 0),
    DETAILS VARCHAR(16777216),
    LINKS VARCHAR(16777216),
    FLIGHT_NUMBER NUMBER (38, 0),
    CREATED_AT TIMESTAMP_NTZ (9),
    UPDATED_AT TIMESTAMP_NTZ (9),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (HISTORY_ID)
);

-- Staging table for landpads
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_LANDPADS (
    LANDPAD_ID VARCHAR(16777216) NOT NULL,
    NAME VARCHAR(256),
    FULL_NAME VARCHAR(512),
    STATUS VARCHAR(50),
    TYPE VARCHAR(50),
    LOCALITY VARCHAR(256),
    REGION VARCHAR(256),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    LANDING_ATTEMPTS NUMBER (38, 0),
    LANDING_SUCCESSES NUMBER (38, 0),
    WIKIPEDIA VARCHAR(16777216),
    DETAILS VARCHAR(16777216),
    LAUNCHES VARCHAR(16777216),
    IMAGES VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ (9),
    UPDATED_AT TIMESTAMP_NTZ (9),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (LANDPAD_ID)
);

-- Staging table for launches
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_LAUNCHES (
    LAUNCH_ID VARCHAR(16777216) NOT NULL,
    FLIGHT_NUMBER NUMBER (38, 0),
    NAME VARCHAR(256),
    DATE_UTC TIMESTAMP_NTZ (9),
    DATE_UNIX NUMBER (38, 0),
    DATE_LOCAL VARCHAR(16777216),
    DATE_PRECISION VARCHAR(16777216),
    STATIC_FIRE_DATE_UTC TIMESTAMP_NTZ (9),
    STATIC_FIRE_DATE_UNIX NUMBER (38, 0),
    NET BOOLEAN,
    WINDOW
        NUMBER (38, 0),
        ROCKET VARCHAR(16777216),
        SUCCESS BOOLEAN,
        FAILURES VARCHAR(16777216),
        UPCOMING BOOLEAN,
        DETAILS VARCHAR(16777216),
        FAIRINGS VARCHAR(16777216),
        CREW VARCHAR(16777216),
        SHIPS VARCHAR(16777216),
        CAPSULES VARCHAR(16777216),
        PAYLOADS VARCHAR(16777216),
        LAUNCHPAD VARCHAR(16777216),
        CORES VARCHAR(16777216),
        LINKS VARCHAR(16777216),
        AUTO_UPDATE BOOLEAN,
        LAUNCH_LIBRARY_ID VARCHAR(16777216),
        CREATED_AT VARCHAR(16777216),
        UPDATED_AT VARCHAR(16777216),
        RAW_DATA VARCHAR(16777216),
        _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
        _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
        _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
        _SDC_DELETED_AT TIMESTAMP_NTZ (9),
        _SDC_SEQUENCE NUMBER (38, 0),
        _SDC_TABLE_VERSION NUMBER (38, 0),
        _SDC_SYNC_STARTED_AT NUMBER (38, 0),
        primary key (LAUNCH_ID)
);

-- Staging table for launchpads
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_LAUNCHPADS (
    LAUNCHPAD_ID VARCHAR(16777216) NOT NULL,
    NAME VARCHAR(256),
    FULL_NAME VARCHAR(512),
    STATUS VARCHAR(50),
    LOCALITY VARCHAR(256),
    REGION VARCHAR(256),
    TIMEZONE VARCHAR(50),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    LAUNCH_ATTEMPTS NUMBER (38, 0),
    LAUNCH_SUCCESSES NUMBER (38, 0),
    ROCKETS VARCHAR(16777216),
    LAUNCHES VARCHAR(16777216),
    DETAILS VARCHAR(16777216),
    IMAGES VARCHAR(16777216),
    CREATED_AT VARCHAR(16777216),
    UPDATED_AT VARCHAR(16777216),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (LAUNCHPAD_ID)
);

-- Staging table for payloads
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_PAYLOADS (
    PAYLOAD_ID VARCHAR(16777216) NOT NULL,
    NAME VARCHAR(256),
    TYPE VARCHAR(100),
    REUSED BOOLEAN,
    LAUNCH VARCHAR(16777216),
    CUSTOMERS VARCHAR(16777216),
    NORAD_IDS VARCHAR(16777216),
    NATIONALITIES VARCHAR(16777216),
    MANUFACTURERS VARCHAR(16777216),
    MASS_KG FLOAT,
    MASS_LBS FLOAT,
    ORBIT VARCHAR(50),
    REFERENCE_SYSTEM VARCHAR(50),
    REGIME VARCHAR(50),
    LONGITUDE FLOAT,
    SEMI_MAJOR_AXIS_KM FLOAT,
    ECCENTRICITY FLOAT,
    PERIAPSIS_KM FLOAT,
    APOAPSIS_KM FLOAT,
    INCLINATION_DEG FLOAT,
    PERIOD_MIN FLOAT,
    LIFESPAN_YEARS FLOAT,
    EPOCH TIMESTAMP_NTZ (9),
    MEAN_MOTION FLOAT,
    RAAN FLOAT,
    ARG_OF_PERICENTER FLOAT,
    MEAN_ANOMALY FLOAT,
    DRAGON VARCHAR(16777216),
    CREATED_AT VARCHAR(16777216),
    UPDATED_AT VARCHAR(16777216),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (PAYLOAD_ID)
);

-- Staging table for roadster
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_ROADSTER (
    ROADSTER_ID VARCHAR(16777216) NOT NULL,
    NAME VARCHAR(256),
    LAUNCH_DATE_UTC TIMESTAMP_NTZ (9),
    LAUNCH_DATE_UNIX NUMBER (38, 0),
    LAUNCH_MASS_KG FLOAT,
    LAUNCH_MASS_LBS FLOAT,
    NORAD_ID NUMBER (38, 0),
    EPOCH_JD FLOAT,
    ORBIT_TYPE VARCHAR(16777216),
    APOAPSIS_AU FLOAT,
    PERIAPSIS_AU FLOAT,
    SEMI_MAJOR_AXIS_AU FLOAT,
    ECCENTRICITY FLOAT,
    INCLINATION FLOAT,
    LONGITUDE FLOAT,
    PERIOD_DAYS FLOAT,
    SPEED_KPH FLOAT,
    SPEED_MPH FLOAT,
    EARTH_DISTANCE_KM FLOAT,
    EARTH_DISTANCE_MI FLOAT,
    MARS_DISTANCE_KM FLOAT,
    MARS_DISTANCE_MI FLOAT,
    WIKIPEDIA VARCHAR(16777216),
    DETAILS VARCHAR(16777216),
    VIDEO VARCHAR(16777216),
    FLICKR_IMAGES VARCHAR(16777216),
    CREATED_AT VARCHAR(16777216),
    UPDATED_AT VARCHAR(16777216),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (ROADSTER_ID)
);

-- Staging table for rockets
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_ROCKETS (
    ROCKET_ID VARCHAR(16777216) NOT NULL,
    NAME VARCHAR(256),
    TYPE VARCHAR(50),
    ACTIVE BOOLEAN,
    STAGES NUMBER (38, 0),
    BOOSTERS NUMBER (38, 0),
    COST_PER_LAUNCH NUMBER (38, 0),
    SUCCESS_RATE_PCT NUMBER (38, 0),
    FIRST_FLIGHT DATE,
    COUNTRY VARCHAR(100),
    COMPANY VARCHAR(100),
    HEIGHT_METERS FLOAT,
    HEIGHT_FEET FLOAT,
    DIAMETER_METERS FLOAT,
    DIAMETER_FEET FLOAT,
    MASS_KG FLOAT,
    MASS_LBS FLOAT,
    PAYLOAD_WEIGHTS VARCHAR(16777216),
    FIRST_STAGE VARCHAR(16777216),
    SECOND_STAGE VARCHAR(16777216),
    ENGINES VARCHAR(16777216),
    LANDING_LEGS VARCHAR(16777216),
    FLICKR_IMAGES VARCHAR(16777216),
    WIKIPEDIA VARCHAR(16777216),
    DESCRIPTION VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ (9),
    UPDATED_AT TIMESTAMP_NTZ (9),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (ROCKET_ID)
);

-- Staging table for ships
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_SHIPS (
    SHIP_ID VARCHAR(16777216) NOT NULL,
    NAME VARCHAR(256),
    LEGACY_ID VARCHAR(16777216),
    MODEL VARCHAR(100),
    TYPE VARCHAR(100),
    ACTIVE BOOLEAN,
    IMO NUMBER (38, 0),
    MMSI NUMBER (38, 0),
    ABS NUMBER (38, 0),
    CLASS NUMBER (38, 0),
    MASS_KG NUMBER (38, 0),
    MASS_LBS NUMBER (38, 0),
    YEAR_BUILT NUMBER (38, 0),
    HOME_PORT VARCHAR(100),
    STATUS VARCHAR(100),
    SPEED_KN FLOAT,
    COURSE_DEG FLOAT,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    LAST_AIS_UPDATE TIMESTAMP_NTZ (9),
    LINK VARCHAR(16777216),
    IMAGE VARCHAR(16777216),
    LAUNCHES VARCHAR(16777216),
    ROLES VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ (9),
    UPDATED_AT TIMESTAMP_NTZ (9),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (SHIP_ID)
);

-- Staging table for starlink
CREATE
OR REPLACE TABLE STG_SPACEX_DATA_STARLINK (
    STARLINK_ID VARCHAR(16777216) NOT NULL,
    VERSION VARCHAR(50),
    LAUNCH VARCHAR(16777216),
    LONGITUDE FLOAT,
    LATITUDE FLOAT,
    HEIGHT_KM FLOAT,
    VELOCITY_KMS FLOAT,
    SPACETRACK VARCHAR(16777216),
    LAUNCH_DATE TIMESTAMP_NTZ (9),
    OBJECT_NAME VARCHAR(100),
    OBJECT_ID VARCHAR(50),
    EPOCH TIMESTAMP_NTZ (9),
    PERIOD_MIN FLOAT,
    INCLINATION_DEG FLOAT,
    APOAPSIS_KM FLOAT,
    PERIAPSIS_KM FLOAT,
    ECCENTRICITY FLOAT,
    MEAN_MOTION FLOAT,
    MEAN_ANOMALY FLOAT,
    ARG_OF_PERICENTER FLOAT,
    RAAN FLOAT,
    SEMI_MAJOR_AXIS_KM FLOAT,
    CREATED_AT TIMESTAMP_NTZ (9),
    UPDATED_AT TIMESTAMP_NTZ (9),
    RAW_DATA VARCHAR(16777216),
    _SDC_EXTRACTED_AT TIMESTAMP_NTZ (9),
    _SDC_RECEIVED_AT TIMESTAMP_NTZ (9),
    _SDC_BATCHED_AT TIMESTAMP_NTZ (9),
    _SDC_DELETED_AT TIMESTAMP_NTZ (9),
    _SDC_SEQUENCE NUMBER (38, 0),
    _SDC_TABLE_VERSION NUMBER (38, 0),
    _SDC_SYNC_STARTED_AT NUMBER (38, 0),
    primary key (STARLINK_ID)
);

-- Create file format for JSON data
CREATE
OR REPLACE FILE FORMAT JSON_FORMAT TYPE = 'JSON' STRIP_OUTER_ARRAY = TRUE ALLOW_DUPLICATE = FALSE;

-- Create error logging table
CREATE
OR REPLACE TABLE LOAD_ERRORS (
    TABLE_NAME VARCHAR(16777216),
    ERROR_TIME TIMESTAMP_NTZ (9),
    ERROR_MESSAGE VARCHAR(16777216),
    ERROR_DATA VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ (9) DEFAULT CURRENT_TIMESTAMP()
);
