{{ config(
    materialized='table',
    alias='pbl_spacex_data_dim_time'
) }}

WITH date_spine AS (
    {{ dbt_utils.date_spine(
        datepart="day",
        start_date="cast('2010-01-01' as date)",
        end_date="cast('2030-12-31' as date)"
    ) }}
),

transformed AS (
    SELECT
        -- date_key will be auto-generated by IDENTITY
        date_day as full_date,
        EXTRACT(YEAR FROM date_day) as year,
        EXTRACT(QUARTER FROM date_day) as quarter,
        EXTRACT(MONTH FROM date_day) as month,
        EXTRACT(WEEK FROM date_day) as week,
        EXTRACT(DAY FROM date_day) as day,
        EXTRACT(DAYOFWEEK FROM date_day) as day_of_week,
        CASE
            WHEN EXTRACT(DAYOFWEEK FROM date_day) IN (6,7) THEN TRUE
            ELSE FALSE
        END as is_weekend
    FROM date_spine
)

SELECT *
FROM transformed
