name: DBT Build DEV
on:
  workflow_run:
    workflows: ["Schemachange DEV", "Extract and Load DEV"]
    types:
      - completed
    branches:
      - dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dbt_build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dbt dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dbt.txt

      - name: Create profiles.yml with environment variables
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
          SNOWFLAKE_USER: ${{ secrets.SPACEX_DATA_DEV_TRANSFORM_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SPACEX_DATA_DEV_TRANSFORM_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ vars.SPACEX_DATA_DEV_TRANSFORM_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ vars.SPACEX_DATA_DEV_TRANSFORM_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ vars.SPACEX_DATA_DEV_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ vars.SPACEX_DATA_DEV_SCHEMA }}
        run: |
          mkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << EOF
          spacex_project:
            target: dev_live
            outputs:
              dev_live:
                type: snowflake
                account: $SNOWFLAKE_ACCOUNT
                user: $SNOWFLAKE_USER
                password: $SNOWFLAKE_PASSWORD
                role: $SNOWFLAKE_ROLE
                database: $SNOWFLAKE_DATABASE
                warehouse: $SNOWFLAKE_WAREHOUSE
                schema: $SNOWFLAKE_SCHEMA
                threads: 4
          EOF

      - name: Run dbt unit tests
        run: |
          cd spacex_project
          dbt test --target dev_live --profiles-dir ~/.dbt

      - name: Run dbt run
        run: |
          cd spacex_project
          dbt run --target dev_live --profiles-dir ~/.dbt
