name: run_singer_dev
on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Install Singer tap dependencies
        run: |
          pip install pytest
          pip install -e .
          pip install singer
          # Add any specific singer tap dependencies here

      - name: Run Singer tap tests
        run: |
          pytest singer_tap/tests/
