name: run_singer_dev
on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dbt dependencies
        run: |
          pip install -r requirements_dbt.txt

      - name: Run dbt unit tests
        run: |
          cd spacex_project
          dbt test -s unit
