name: Schemachange UAT
on:
  push:
    branches:
      - uat
    paths:
      - "db_setup/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  schemachange:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: uat
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install schemachange
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          python -m pip install --upgrade pip
          pip install schemachange

      - name: Run schemachange
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
          SNOWFLAKE_USER: ${{ secrets.SPACEX_DATA_UAT_CICD_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SPACEX_DATA_UAT_CICD_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ vars.SPACEX_DATA_UAT_CICD_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ vars.SPACEX_DATA_UAT_CICD_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ vars.SPACEX_DATA_UAT_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ vars.SPACEX_DATA_UAT_SCHEMA }}
          ENVIRONMENT: uat
        run: |
          # Run schemachange to apply database changes
          echo "Step 2: Running schemachange with config file for UAT"
          export SNOWFLAKE_PASSWORD=$SNOWFLAKE_PASSWORD
          schemachange deploy \
            -f $GITHUB_WORKSPACE/db_setup \
            --config-file $GITHUB_WORKSPACE/db_setup/schemachange-config.yml \
            -a $SNOWFLAKE_ACCOUNT \
            -u $SNOWFLAKE_USER \
            -r $SNOWFLAKE_ROLE \
            -w $SNOWFLAKE_WAREHOUSE \
            -d $SNOWFLAKE_DATABASE \
            -c ${SNOWFLAKE_DATABASE}.SCHEMACHANGE.CHANGE_HISTORY \
            --create-change-history-table \
            --verbose
