name: Schemachange UAT
on:
  push:
    branches:
      - uat
    paths:
      - "db_setup/**"

jobs:
  schemachange:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install schemachange
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          python -m pip install --upgrade pip
          pip install schemachange

      - name: Run schemachange
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_ID }}
          SNOWFLAKE_USER: ${{ secrets.SPACEX_DATA_DEV_CICD_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SPACEX_DATA_DEV_CICD_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ vars.SPACEX_DATA_DEV_CICD_ROLE }}
          SNOWFLAKE_WAREHOUSE: ${{ vars.SPACEX_DATA_DEV_CICD_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ vars.SPACEX_DATA_DEV_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ vars.SPACEX_DATA_DEV_SCHEMA }}
        run: |
          # Run schemachange to apply database changes
          echo "Step 2: Running schemachange"
          schemachange \
            --config-folder $GITHUB_WORKSPACE/db_setup \
            --snowflake-account $SNOWFLAKE_ACCOUNT \
            --snowflake-user $SNOWFLAKE_USER \
            --snowflake-password $SNOWFLAKE_PASSWORD \
            --snowflake-role $SNOWFLAKE_ROLE \
            --snowflake-warehouse $SNOWFLAKE_WAREHOUSE \
            --snowflake-database $SNOWFLAKE_DATABASE \
            --create-change-history-table \
            --verbose
